version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: workflow-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MinhaSenha123.
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet

  workflowapi:
    build:
      context: .
      dockerfile: WorkflowAPI/Dockerfile
    container_name: workflow-api
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      -  ConnectionStrings__WorkflowDatabase=Server=workflow-sql,1433;Database=WorkflowDb;User Id=sa;Password=MinhaSenha123.;TrustServerCertificate=True
    networks:
      - appnet

  workflowfrontend:
    build:
      context: ./workflow-frontend
      dockerfile: Dockerfile
    container_name: workflow-frontend
    ports:
      - "4200:80"
    depends_on:
      - workflowapi
    networks:
      - appnet

volumes:
  sql_data:

networks:
  appnet:
    driver: bridge
